enum UserAction {
  TAKE_POSITION_IN_PORTFOLIO = 1,
  MOVE_POSITION_FROM_ONE_PORTFOLIO_TO_ANOTHER = 2,
  GET_TOTAL_POSITION_TAKEN = 3,
  GET_PORTFOLIO_LIST = 4,
  GET_PORTFOLIO_DETAILS = 5,
}
export default UserAction;